### ISSUE TITLE
naming convention for list of lists for storing categorical and numerical column names

### ISSUE THREAD

**Issue by arunmarria** [UBC-MDS/laundRy#25]
We'll need to ensure that all our functions use same name for the lists with in the list returned by @cgostic function so we can fetch relevant column names by using those list names. 

 We may create our own names as of now but eventually we'll need to have consistency in terms of naming conventions for the list(of lists) which all our functions will use!

**Comment by zanderhinton** [comment]
Right.  And actually it's a "list of vectors", just reviewing my R stuff now.   In my mind it's something like:

col_categorize <- list("numeric" <- c("mpg", "age"),  "categorical" <- c("brand"))

**Comment by arunmarria** [comment]
But didn't @cgostic said that we will be returning list of lists? `list(list_numeric, list_categoric)`, This way we/users can access elements in traditional R way i.e `col_categorize$list_numeric` ? What y'all think?

**Comment by zanderhinton** [comment]
I think in R list is just a vector which holds different atomic types.  Each of our "lists" should hold 1 type, character. 
col_categorize$numeric will return "mpg", "age" in the way I specified.

**Comment by arunmarria** [comment]
That's a good point. Thanks Alex, lets stick to that!

**Comment by zanderhinton** [comment]
Passing in column names quoted like above ("mpg"), does have issues, as df$"mpg" won't return anything.

**Comment by cgostic** [comment]
Yes the above is correct! Thanks for clarifying. I currently have a list of vectors as below:

```
list(numeric = c('col1', 'col2', 'col3'), categorical = c('col4', 'col5'))
```

So that the output can be referenced as 

```
cat <- categorize(df)
cat$numeric
>>> 'cat1'  'cat 2'  'cat3'
```

@arunmarria @zanderhinton @amank90
