### ISSUE TITLE
Categorize function

### ISSUE THREAD

**Issue by zanderhinton** [UBC-MDS/laundRy#6]
Name: categorize()

This will take in a df and parse each column into 'numeric','categorical', and 'text' categories. It will return a list in the following format:

{numeric = list('col1','col2','col3'), categorical = list('col4','col5'), text = list('col6','col7'))

Value:

- These lists can be passed into our transform function, or a more complex transformer pipeline.

To Do:

 - [x] Create function skeleton in .R file
 - [x] Write docstring

**Comment by cgostic** [comment]
The way I decided to separate numeric columns, which could be either categorical or numeric, was by adding a parameter max_cat (int) to the function. The default value is 10.

If there are more than max_cat unique values in a column with dtype numeric, the column is categorized as numeric.
If there are <= max_cat unique values in a column with dtype numeric, the column is categorized as categorical.
A column specified as dtype 'factor' is categorized as categorical no matter the max_cat specification, so a user may override max_cat for certain columns of interest by setting this dtype.

Columns that are not categorized as categorical or numeric are not included in the output list of vectors.
